name: Get-Image-Hermes-Agent
on: workflow_dispatch
jobs:
  download_image:
    runs-on: ubuntu-latest
    steps:
      - name: Pull and Save Image
        run: |
          docker pull hermes-agent
          docker save -o hermes-agent.tar hermes-agent
      - name: Upload to Page
        uses: actions/upload-artifact@v4
        with:
          name: hermes-image
          path: hermes-agent.tar
