name: Get-Image-N8N-runners
on: workflow_dispatch
jobs:
  download_image:
    runs-on: ubuntu-latest
    steps:
      - name: Pull and Save Image
        run: |
          docker pull n8nio/runners:2.38.2
          docker save -o n8n-runners.tar n8nio/runners:2.38.2
      - name: Upload to Page
        uses: actions/upload-artifact@v4
        with:
          name: n8n-runners-image
          path: n8n-runners.tar
